### ISSUE TITLE
搜索和更新问题

### ISSUE THREAD

**Issue by ZhongFuCheng3y** [shuibaco/bitcron-theme-ink#1]
你好，搜索的功能能不能针对文章的标题来进行搜索？搜索功能貌似不太好用。

我看更新后的模版有标签这么一个功能，但我的显示不了...请问这是什么原因。

**Comment by shuibaco** [comment]
@ZhongFuCheng3y 您好，首先感谢你使用我的主题。

> 搜索的功能能不能针对文章的标题来进行搜索？搜索功能貌似不太好用。

搜索功能是Bitcron系统提供的，模板解决不了这个问题。如果觉得搜索功能有哪里不好用，请直接发邮件给pi@bitcron.com反馈。

> 我看更新后的模版有标签这么一个功能，但我的显示不了...请问这是什么原因。

你得在文章meta里写上标签：https://faq.bitcron.com/read/markdown_metadata
我看你应该是没写的，因为首页标题下面都会显示分类和标签。另外可以到后台自定义菜单栏添加相关的菜单，比如标签是`/tags`。

希望能够解决你的问题。有什么其他疑问欢迎反馈！祝好。

**Comment by ZhongFuCheng3y** [comment]
@shuibaco 感谢您的回答，原来是要写meta的。

还有一个问题就是：about页面中的内容，为什么我返回的数据是没有样式的？您所说的在根目录下创建about.jade，根目录指的是bitcron还是template？创建出来的about.jade要写的仅仅是“自己想要写的内容“吗？

**Comment by shuibaco** [comment]
@ZhongFuCheng3y 啊，实在对不起，我才发现我的about页面写错了。应该是新建一个`about.md`文件。你的理解是正确的，根目录是指bitcron，如果是template文件夹我会指明的。

非常感谢你的反馈，我去修改一下about页面。

**Comment by ZhongFuCheng3y** [comment]
@shuibaco  一个一个修改的....哎

**Comment by shuibaco** [comment]
@ZhongFuCheng3y 辛苦了，我之前也是，所以才想问问有没有更有效率的办法。
